### ISSUE TITLE
Unlike Post not working, remove from array list does not happen

### ISSUE THREAD

**Issue by divyayadav1606** [accountabilibuddies/accountabilibuddies#116]

**Comment by deonna** [comment]
What were the expected and actual outputs? What was the original input?

**Comment by divyayadav1606** [comment]
When a user unlikes a post need to remove him from the likeList in Post. But the API is not raving current user object from the likeliest

**Comment by deonna** [comment]
Just double-checked this logic, and the filter list is working. The issue is with the logic in the code

Specifically [this line](https://github.com/accountabilibuddies/accountabilibuddies/blob/6fe48bbbc4922ef1dab4d4b8d6bc6a274f02cefb/app/src/main/java/com/accountabilibuddies/accountabilibuddies/network/APIClient.java#L363):

```java
post.addAllUnique("likeList", users);
```

The method should be post.put("likeList", users). The line that is currently in the codebase adds users to the existing likeList instead of replacing it with the list that does not contain the current user. Will merge my fix.
